# Generated by Django 6.0.5 on 2026-05-29 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('monto_limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'gasto'}, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='categorias.categoria')),
            ],
            options={
                'ordering': ['-anio', '-mes', 'categoria__nombre'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'anio', 'mes'), name='presupuesto_unico_por_categoria_periodo'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='presupuesto_mes_valido'), models.CheckConstraint(condition=models.Q(('monto_limite__gt', 0)), name='presupuesto_monto_positivo')],
            },
        ),
    ]
