# Generated by Django 6.0.5 on 2026-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='solo_recibe_traspasos',
            field=models.BooleanField(default=False, help_text='Si se activa, esta cuenta solo puede recibir traspasos.'),
        ),
    ]
