# Generated by Django 6.0.5 on 2026-06-01 00:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaPagoProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fecha de pago programada',
                'verbose_name_plural': 'Fechas de pago programadas',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad_descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje de recorte sobre el gasto diario recomendado.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categorias_excluidas', models.ManyToManyField(blank=True, help_text='Gastos de estas categorias no cuentan para la alerta diaria (ej: cuentas, servicios).', limit_choices_to={'tipo': 'gasto'}, related_name='configuraciones_kpi_excluidas', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Configuracion KPI',
                'verbose_name_plural': 'Configuracion KPI',
            },
        ),
    ]
