# Generated by Django 6.0.5 on 2026-06-01 01:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFijoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('frecuencia', models.CharField(choices=[('unica', 'Una vez'), ('mensual', 'Mensual')], default='mensual', max_length=12)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto fijo programado',
                'verbose_name_plural': 'Gastos fijos programados',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='fechapagoprogramada',
            name='es_pago_principal',
            field=models.BooleanField(default=True, help_text='Se usa para calcular los dias del tramo corto (hasta el proximo pago principal).'),
        ),
        migrations.AddField(
            model_name='fechapagoprogramada',
            name='frecuencia',
            field=models.CharField(choices=[('unica', 'Una vez'), ('mensual', 'Mensual')], default='mensual', max_length=12),
        ),
        migrations.AddField(
            model_name='fechapagoprogramada',
            name='monto_esperado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
