# Generated by Django 6.0.5 on 2026-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reestructura_base_y_limpieza_financiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionkpi',
            name='fecha_proximo_corte',
            field=models.DateField(blank=True, help_text='Fecha manual del proximo corte para calcular gasto diario permitido.', null=True),
        ),
    ]
