# Generated by Django 6.0.5 on 2026-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
