# Generated by Django 6.0.5 on 2026-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_cuenta_sugerida_alter_categoria_tipo'),
        ('cuentas', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE movimientos_movimiento SET tipo = 'traspaso' WHERE tipo = 'transferencia';",
            reverse_sql="UPDATE movimientos_movimiento SET tipo = 'transferencia' WHERE tipo = 'traspaso';",
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('traspaso', 'Traspaso')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuenta_destino__isnull', False), ('tipo', 'traspaso')), models.Q(('cuenta_destino__isnull', True), ('tipo__in', ['ingreso', 'gasto'])), _connector='OR'), name='movimiento_destino_valido_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('cuenta_origen', models.F('cuenta_destino')), ('tipo', 'traspaso'), _negated=True), name='movimiento_traspaso_cuentas_distintas'),
        ),
    ]
