# Generated by Django 6.0.5 on 2026-05-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('cuentas', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuotas_totales', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('categoria_pago', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'gasto'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='categorias.categoria')),
                ('cuenta_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='cuentas.cuenta')),
            ],
            options={
                'ordering': ['-activa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_interes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.credito')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movimientos.movimiento')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
