# Generated by Django 6.0.5 on 2026-06-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_cuenta_sugerida_alter_categoria_tipo'),
        ('creditos', '0001_initial'),
        ('cuentas', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['credito_id', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='EventoCuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('reversa', 'Reversa')], max_length=12)),
                ('fecha_evento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movimiento_id_referencia', models.PositiveIntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='pagocredito',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='pagocredito',
            name='movimiento',
        ),
        migrations.AlterField(
            model_name='credito',
            name='cuenta_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='entidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('monto_original__gt', 0)), name='credito_monto_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('cuotas_totales__gt', 0)), name='credito_cuotas_totales_positivas'),
        ),
        migrations.AddField(
            model_name='cuotacredito',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='creditos.credito'),
        ),
        migrations.AddField(
            model_name='cuotacredito',
            name='cuenta_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_credito_pagadas', to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='cuotacredito',
            name='movimiento_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuota_credito_pagada', to='movimientos.movimiento'),
        ),
        migrations.AddField(
            model_name='eventocuotacredito',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='eventocuotacredito',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='creditos.cuotacredito'),
        ),
        migrations.DeleteModel(
            name='PagoCredito',
        ),
        migrations.AddConstraint(
            model_name='cuotacredito',
            constraint=models.UniqueConstraint(fields=('credito', 'numero'), name='cuota_credito_unica_por_numero'),
        ),
        migrations.AddConstraint(
            model_name='cuotacredito',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='cuota_credito_monto_positivo'),
        ),
    ]
